// LOCALHOST ### 
GET http://localhost:8080/contacts
### 
GET http://localhost:8080/contacts/650b7efee351b199a40b773e
### 
GET http://localhost:8080/contacts/650b802ce351b199a40b7741
### 
GET http://localhost:8080/contacts/650b808fe351b199a40b7742


### Create contact
POST http://localhost:8080/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName": "Oyunkhand",
    "lastName": "Bayart",
    "email":"oyunkhandb@gmail.com",
    "favoriteColor":"pink",
    "birthday":"03/04/1966"
}

### Update 
PUT http://localhost:8080/contacts/651669f4056b322412163775 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Oyunkhand",
    "lastName": "Bayart",
    "email":"mongolia67@gmail.com",
    "favoriteColor":"turquoise",
    "birthday":"03/04/1986"
}

### Remove 
DELETE http://localhost:8080/contacts/651669f4056b322412163775 HTTP/1.1



// RENDER WEEK-3 
### All contacts
GET https://week3-personal-assignment.onrender.com/contacts

// Individual by ID
### 
GET https://week3-personal-assignment.onrender.com/contacts/650b7efee351b199a40b773e

###
GET https://week3-personal-assignment.onrender.com/contacts/650b802ce351b199a40b7741

###
GET https://week3-personal-assignment.onrender.com/contacts/650b808fe351b199a40b7742

###
POST https://week3-personal-assignment.onrender.com/contacts/
Content-Type: application/json

{
    "firstName": "Boldbayar",
    "lastName": "Oyunkhand",
    "email":"bolddbayar@gmail.com",
    "favoriteColor":"navy blue",
    "birthday":"06/02/1997"
}

###
PUT https://week3-personal-assignment.onrender.com/contacts/65165da2174eca52f093dcaa
Content-Type: application/json

{
    "firstName": "Boldbayar",
    "lastName": "Purevdavaa",
    "email":"pbdboldbayar@gmail.com",
    "favoriteColor":"green",
    "birthday":"12/02/1994"
}

###
DELETE https://week3-personal-assignment.onrender.com/contacts/65165da2174eca52f093dcaa





// Render week-2 below
### 
GET https://week2-personal-assignment.onrender.com/contacts
###
GET https://week2-personal-assignment.onrender.com/contacts/650b7efee351b199a40b773e
###
GET https://week2-personal-assignment.onrender.com/contacts/650b802ce351b199a40b7741
###
GET https://week2-personal-assignment.onrender.com/contacts/650b808fe351b199a40b7742


